cardano-api(gen,test): Remove unnecessary function; Reformat imports
IntersectMBO/cardano-node pull request #3288
Opened 2021-10-11 19:14 UTC by cblp

No need to convert a Hedgehog group to a Tasty one since Tasty can incorporate Hedgehog properties directly

2021-10-12 16:22 UTC, Jimbo4350 requested changes

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Json.hs
> -import           Cardano.Api
`Cardano.Api` imports should be at the top at it was.

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/KeysByron.hs
> -import           Cardano.Api
Same here

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Metadata.hs
> -import           Cardano.Api
Same here.

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Address.hs
> -import           Cardano.Api
Same here

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Bech32.hs
> -import           Hedgehog (Property, discover)
Generally we leave the test modules last.

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Envelope.hs
> -import           Cardano.Api
Same here

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Ord.hs
> -import           Cardano.Api
Same here

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/RawBytes.hs
> -import           Cardano.Api
Same here

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Script.hs
> -import           Cardano.Api
Same here.

2021-10-12 16:22 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Typed/Value.hs
> -import           Cardano.Api.Shelley
Same here

2021-10-13 16:13 UTC, Jimbo4350 commented on cardano-api/test/Test/Cardano/Api/Json.hs
> -import           Cardano.Api
You're right, I just had a look in `cardano-api`

2021-10-14 12:10 UTC, cblp commented
bors merge

2021-10-14 12:34 UTC, merged