add changelog
IntersectMBO/cardano-node pull request #5952
Opened 2024-08-16 12:24 UTC by aleeusgr

# Description
Intersect MBO Open Source Office governance policy requires that CHANGELOG.md exists at the top level of the project.
The log should link to individual logs for the components. #5874 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2024-08-19 13:33 UTC, carbolymer requested changes
It does not render readably: https://github.com/IntersectMBO/cardano-node/blob/9bdf7ab901bd4f20a0b937175aac73f801d5b893/CHANGELOG.md . Would you mind using markdown links to link the sub-changelogs?

2024-08-19 13:34 UTC, carbolymer commented on CHANGELOG.md
> +## 0.1.0.0 -- August 2024
This version number is incorrect

2024-08-20 11:21 UTC, aleeusgr commented
Hi! @carbolymer 

I added the changes you requested: removed version number and added hyperlinks respective .md's;

2024-08-22 09:04 UTC, carbolymer reviewed
LGTM, but can you squash the commits together?

2024-08-22 13:14 UTC, disassembler requested changes

2024-08-22 13:14 UTC, disassembler commented on CHANGELOG.md
> +[trace-resources](https://github.com/IntersectMBO/cardano-node/blob/master/trace-resources/CHANGELOG.md) <br>
Use bullets instead of <br> at end of line

2024-08-23 05:29 UTC, closed without merging